In [ ]:
T = (1)
print(T + 10)

11


In [ ]:
num = 9
for i in range(2,num):
  if num%i == 0:
    print('Not Prime')
    break
else:
  print('Prime')

Not Prime


In [ ]:
n = 523
for i in range(len(str(n))):
  a = n%10
  n = n//10
  print(a,end='')

def rev(n):
  rev = ''
  for i in range(len(str(n))):
    a = n%10
    n = n//10
    rev = rev + str(a)
  return rev

print(rev(n))

325


In [ ]:
l = [6,98,34]
d = {}
for num in l:
  l1 = []
  for i in range(1,num+1):
    if num%i == 0:
      l1.append(i)
  d[num] = l1
print(d)

{6: [1, 2, 3, 6], 98: [1, 2, 7, 14, 49, 98], 34: [1, 2, 17, 34]}


In [ ]:
n = int(input('Enter a number:'))
c=0
while n != 1234:
  if c>=3:
    print('Locked')
    break
  else:
    n = int(input('Enter a number:'))
    c= c+1
    print('Correct')

Enter a number:1
Enter a number:2
Correct
Enter a number:6
Correct
Enter a number:4
Correct
Locked


In [ ]:
n = 153
temp = n
sum = 0
for i in range(3):
  a = n%10
  sum = sum + a**3
  n = n//10

print(sum)

if sum == temp:
  print('Armstrong')
else:
  print('Not Armstrong')

153
Armstrong


In [ ]:
n = int(input('Enter a number:'))
for i in range(1,3):
  if n != 1234:
    n = int(input('Enter a number again:'))
  else:
    if n == 1234:
      print('Correct')
      break
    else:
      print('Locked')

Enter a number:1234
Correct


In [102]:
n = 16
l=[]
for i in range(2,n):
  if n%i == 0:
    l.append(i)
  else:
    continue

print('Factors list:',l)
#print('Sum of factors list:',sum(l))

if len(l) == 0:
  print('Prime')
else:
  print('Composite')

Factors list: [2, 4, 8]
Composite


In [106]:
n = 28
l = []
for i in range(1,n):
  if n%i == 0:
    l.append(i)

print(l)

sum = 0
for i in l:
  sum = sum + i

print('Sum:',sum)

if sum == n:
  print('Perfect')
else:
  print('Not Perfect')

[1, 2, 4, 7, 14]
Sum: 28
Perfect


In [111]:
n = 7
a = 0
b = 1
for i in range(0,n):
  print(a,end=' ')
  c = a+b
  a = b
  b = c

0 1 1 2 3 5 8 

In [117]:
l = [3,2,1,6,5]
print(l)
print(list(reversed(l)))
print(sorted(l))
print(sorted(l,reverse=True))

[3, 2, 1, 6, 5]
[5, 6, 1, 2, 3]
[1, 2, 3, 5, 6]
[6, 5, 3, 2, 1]


In [123]:
l = [3,1,-2,8,4]
m = l[0]
for i in l:
  if m > i:
    m = i
    continue
print('Smallest number:',m)


-2


In [144]:
n = 5
for i in range(1,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i-1):
    print('*_',end= '')
  print('*')

    *
   *_*
  *_*_*
 *_*_*_*
*_*_*_*_*


In [151]:
n = 5
for i in range(1,n+1):
  for j in range(1,i+1):
    print('* ',end='')
  print('\r')

* 
* * 
* * * 
* * * * 
* * * * * 


In [127]:
import numpy as np

l = [ [2,4,6,8,10],  4]
a = l[0]
b = l[1]

avg = np.mean(a)

if avg > b:
  print('True')
else:
  print('False')

True


In [160]:
m = 4
n = 5
f = [0]*n
f = [list(f) for i in range(m)]

for i in range(0,m):
    for j in range(0,n):
        if i==0 or i==m-1 or j==0 or j==n-1:
            f[i][j] = 1
        else:
            f[i][j] = 0

for i in f:
    print(i)

[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]


In [ ]:
n = int(input('Enter a number:'))
def fact(n):
  if n < 0:
    return -1
  elif n == 0:
    return 1
  else:
    return n*fact(n-1)

print(fact(n))

Enter a number:9
362880


In [ ]:
import numpy as np
X = np.arange(1,11)
Y = np.array([10,9,8,7,6,5,4,3,2,1])
Z = np.add(X,Y)
print(Z)

[11 11 11 11 11 11 11 11 11 11]


In [ ]:
import pandas as pd
S1 = pd.Series([0,2,4,6,8,10,12])
S2 = pd.Series([0,3,6,9,12,15])

print(S1)
print(S2)

0     0
1     2
2     4
3     6
4     8
5    10
6    12
dtype: int64
0     0
1     3
2     6
3     9
4    12
5    15
dtype: int64


In [ ]:
S1[S1.isin(S2)]

0     0
3     6
6    12
dtype: int64

In [ ]:
S1[S1.isin(S2)].index == S2[S2.isin(S1)].index

array([ True, False, False])

In [ ]:
msg = "crocoDILE"
price = "125"
sample = "0123456789"

In [ ]:
print(msg.upper())
print(msg.lower())
print(msg.capitalize())
print(msg.startswith('C'))
print(msg.endswith('E'))
print(msg.index('c'))
print(msg.count('o'))
print(price.isdigit())
print('this is shruthi'.capitalize())
print('this is shruthi'.title())

CROCODILE
crocodile
Crocodile
False
True
0
2
True
This is shruthi
This Is Shruthi


In [ ]:
print(sample[0])
print(sample[:])
print(sample[0:3])  #0,1,2
print(sample[:4])
print(sample[4:])

0
0123456789
012
0123
456789


In [ ]:
print(sample[-1])
print(sample[-2:])
print(sample[::-1])
print(sample[-5:-2])

9
89
9876543210
567


In [ ]:
s1 = 'This is Shruthi from TCS'
print(s1.split(' '))

['This', 'is', 'Shruthi', 'from', 'TCS']


In [ ]:
M1 = 'English 75 Maths 80 Science 95'
M2 = M1.split()
print("New List:",M2)
l=[]
for s in M2[1::2]:
  l.append(int(s))
print("Scores list:",l)
print("Total: ",sum(l))
print("Average: ",round(sum(l)/len(l),2))

New List: ['English', '75', 'Maths', '80', 'Science', '95']
Scores list: [75, 80, 95]
Total:  250
Average:  83.33


In [ ]:
M1 = 'English 75 Maths 80 Science 95'
M2 = M1.split()
print("New List:",M2)
l=[]
for word in M2 :
  if word.isdigit() :
    l.append( int(word))
print('Scores List: ',l)
print('Total Scores ' , sum(l))
print('Average',round(sum (l)/len(l),2))

New List: ['English', '75', 'Maths', '80', 'Science', '95']
Scores List:  [75, 80, 95]
Total Scores  250
Average 83.33


In [ ]:
names = 'Shruthi Sony,Sathvik Lucky,Saritha Sari,Balachander Chandu'
N1 = names.split(',')
for i in N1:
  name1 = i.split()
  print("Dear "+name1[1]+'.'+name1[0][0])

Dear Sony.S
Dear Lucky.S
Dear Sari.S
Dear Chandu.B


In [ ]:
weights = [12,11,13,14,15]
dict1={}
for i in weights:
  dict1[i] = round(i*0.45,2)
print(dict1)

{12: 5.4, 11: 4.95, 13: 5.85, 14: 6.3, 15: 6.75}


In [ ]:
visibility = [1,2,3,4,5,6]

dict1={}
for i in visibility:
  if i<=2:
    fog_level = 'ThickFog'
  elif 3<=i<=5:
    fog_level = 'Moderate'
  else:
    fog_level = 'low'
  dict1[i]= fog_level
print(dict1)

{1: 'ThickFog', 2: 'ThickFog', 3: 'Moderate', 4: 'Moderate', 5: 'Moderate', 6: 'low'}


In [ ]:
days = ['M','W','F']
medicines = ['Vit','Ca','Zn']
dictt2={}
for d,m in zip(days,medicines):
  dictt2[d] = m
print(dictt2)

{'M': 'Vit', 'W': 'Ca', 'F': 'Zn'}


In [ ]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
dict3=dict1|dict2
dict3

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

In [ ]:
sampleDict = {
    "class": {
        "student": {
            "name": "Mike",
            "marks": {
                "physics": 70,
                "history": 80
            }
        }
    }
}
sampleDict['class']['student']['marks']['history']

80

In [ ]:
employees = ['Kelly', 'Emma']
defaults = {"designation": 'Developer', "salary": 8000}
res = dict.fromkeys(employees, defaults)
print(res)

{'Kelly': {'designation': 'Developer', 'salary': 8000}, 'Emma': {'designation': 'Developer', 'salary': 8000}}


In [ ]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"}

# Keys to extract
keys = ["name", "salary"]
dict1={}

for k in keys:
    dict1[k]=sample_dict[k]
print(dict1)

{'name': 'Kelly', 'salary': 8000}


In [ ]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}

sample_dict['location'] =sample_dict['city']
del sample_dict['city']
sample_dict

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'New york'}

In [ ]:
sample_dict = {'a': 100, 'b': 200, 'c': 300}

if 200 in sample_dict.values():
  print("YES")

YES


In [ ]:
sample_dict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}
min_value = min(sample_dict.values())
min_key = next(key for key, value in sample_dict.items() if value == min_value)

# Print the value corresponding to the minimum key
print(sample_dict[min_key])


65


In [ ]:
sample_dict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}
print(sample_dict)
minvalue = min(sample_dict.values())
print(minvalue)
minkey = [key for key,value in sample_dict.items() if value == minvalue]
print(minkey)

{'Physics': 82, 'Math': 65, 'history': 75}
65
['Math']


In [ ]:
import numpy as np
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
l = []
for i in sampleArray:
  l.append(i[2])
res = np.array(l)
print(res)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]


In [ ]:
l = [i for i in range(100,200,10)]
l1 = np.array(l)
l2 = l1.reshape(5,2)
print(l2)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print(sampleArray[::2,1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [ ]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrayThree = arrayOne + arrayTwo
print(arrayThree)
res = arrayThree **2
print(res)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [ ]:
l = [i for i in range(10,34,1)]
l1 = np.array(l)
l2 = l1.reshape(8,3)
print(l2)
l3 = l2.reshape(4,2,3)
print(l3)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]

 [[22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]]]


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [ ]:
data = np.delete(sampleArray,2,1)  #np.delete(array,row/column number,axis no 1=col,0=row)
print(data)

# newColumn = np.array([[10,10,10]])
# data1 = np.insert(data,1,newColumn,1)

# print(data1)

[[34 43]
 [82 22]
 [53 94]]


In [ ]:
data = np.delete(sampleArray,0,0)
print(data)

[[82 22 12]
 [53 94 66]]


In [ ]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')
df.shape

(61, 10)

In [ ]:
df.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [ ]:
df = df.sort_values(by=['price'],ascending=False)
df.head()

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0

In [ ]:
df [['company','price']]
#df['price'].max()

company    price
35  mercedes-benz  45400.0
11            bmw  41315.0
34  mercedes-benz  40960.0
46        porsche  37028.0
12            bmw  36880.0
..            ...      ...
27          mazda   5195.0
13      chevrolet   5151.0
22          isuzu      NaN
23          isuzu      NaN
47        porsche      NaN

[61 rows x 2 columns]

In [ ]:
df1 = df.groupby('company')
print(df1.get_group('toyota'))

    index company body-style  wheel-base  length engine-type num-of-cylinders  \
54     79  toyota      wagon       104.5   187.8        dohc              six   
53     71  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
48     66  toyota  hatchback        95.7   158.7         ohc             four   

    horsepower  average-mileage    price  
54         156               19  15750.0  
53          62               27   8778.0  
52          62               27   7898.0  
51          62               31   6918.0  
50          62               31   6488.0  
49          62               31   6338.0  
48          62               35   5348.0  


In [ ]:
df['company'].value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
porsche          3
jaguar           3
alfa-romero      3
honda            3
isuzu            3
chevrolet        3
volvo            2
dodge            2
Name: count, dtype: int64

In [ ]:
print(df.head(5))
print(df.tail(5))

In [ ]:
df1 = df.groupby('company')
print(df1['company','average-mileage'].mean())

In [ ]:
prev = 0
for i in range(0,11):
  print('curr:',i)
  sum = prev + i
  print('sum:',sum)
  print('prev:',prev)
  prev = i

curr: 0
sum: 0
prev: 0
curr: 1
sum: 1
prev: 0
curr: 2
sum: 3
prev: 1
curr: 3
sum: 5
prev: 2
curr: 4
sum: 7
prev: 3
curr: 5
sum: 9
prev: 4
curr: 6
sum: 11
prev: 5
curr: 7
sum: 13
prev: 6
curr: 8
sum: 15
prev: 7
curr: 9
sum: 17
prev: 8
curr: 10
sum: 19
prev: 9


In [ ]:
a = 'sony'
for i in range(0,len(a)):
    if i%2 == 0:
      print(a[i],end=' ')

s n 

In [ ]:
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
list3 = list1+list2
l=[]
for i in range(0,len(list1)):
  if list1[i]%2 != 0:
    l.append(list1[i])

for i in range(0,len(list2)):
  if list2[i]%2 == 0:
    l.append(list2[i])

print(l)

[25, 35, 40, 60, 90]


In [ ]:
a = 1234
print(int(a/10))
print(a%10)

123
4


In [ ]:
for num in range(6):
    for i in range(num):
        print (num, end=" ") #print number
    # new line after each row to display pattern correctly
    print("\n")



1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



In [ ]:
def power(b,p):
  return b**p

print(power(2,5))

32


In [ ]:
n = 1234
#output = 4321
for i in range(0,4):
  while n > 0:
    b = n%10
    n = n//10
    print(b,end='')

4321

In [ ]:
#123 -- input
#213 -- output

n = '12345678'
rev = ''
if len(n)%2==1:
  for i in range(0,len(n)-1,2):
    #print(i)
    rev = rev + n[i+1] + n[i]
  rev = rev + n[-1]

else:
  for i in range(0, len(n), 2):
    rev = rev + n[i+1] + n[i]

print(rev)

21436587


In [ ]:
import pandas as pd

In [ ]:
data = {
    'salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'manager': ['Manager1', 'Manager1', 'Manager2', 'Manager1', 'Manager2', 'Manager3'],
    'date': ['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-01', '2023-10-02', '2023-10-03'],
    'item_sold': ['Item1', 'Item2', 'Item3', 'Item1', 'Item2', 'Item3'],
    'price': [10, 20, 30, 10, 20, 30],
    'sales_amount': [100, 200, 300, 100, 200, 300],
    'region': ['North', 'South', 'East', 'North', 'East', 'West']
}

sales_data = pd.DataFrame(data)
print(sales_data)

  salesperson   manager        date item_sold  price  sales_amount region
0       Alice  Manager1  2023-10-01     Item1     10           100  North
1         Bob  Manager1  2023-10-02     Item2     20           200  South
2     Charlie  Manager2  2023-10-03     Item3     30           300   East
3       David  Manager1  2023-10-01     Item1     10           100  North
4         Eve  Manager2  2023-10-02     Item2     20           200   East
5       Frank  Manager3  2023-10-03     Item3     30           300   West


In [ ]:
grouped_sales = sales_data.groupby('manager')['salesperson'].apply(list).reset_index()
grouped_sales.columns = ['manager', 'list_of_salesmen']
print(grouped_sales)

    manager     list_of_salesmen
0  Manager1  [Alice, Bob, David]
1  Manager2       [Charlie, Eve]
2  Manager3              [Frank]


In [ ]:
data = {
    'employee_id': [101, 102, 103, 104, 105],
    'age': [25, 30, 22, 30, 28],
    'company': ['CompanyA', 'CompanyB', 'CompanyA', 'CompanyB', 'CompanyC']
}

employee_data = pd.DataFrame(data)
print(employee_data)

   employee_id  age   company
0          101   25  CompanyA
1          102   30  CompanyB
2          103   22  CompanyA
3          104   30  CompanyB
4          105   28  CompanyC


In [ ]:
sorted_data = employee_data.sort_values(by='age',ascending=False).reset_index()
print(sorted_data)

   index  employee_id  age   company
0      1          102   30  CompanyB
1      3          104   30  CompanyB
2      4          105   28  CompanyC
3      0          101   25  CompanyA
4      2          103   22  CompanyA


In [ ]:
print(sorted_data['employee_id'].iloc[0])
print(sorted_data['company'].iloc[0])

102
CompanyB


In [ ]:
myList = [1,2,3,7,5]
myReversedList = list(reversed(myList))
print(myReversedList)

[5, 7, 3, 2, 1]


In [ ]:
s = pd.Series([1, 2, 3, 4,5], index= ['a','b','c','d','e'])
t = pd.Series([5, 4, 3, 2, 1], index = ['c','d','b','e','a'])
print(s)
print(t)

a    1
b    2
c    3
d    4
e    5
dtype: int64
c    5
d    4
b    3
e    2
a    1
dtype: int64


In [ ]:
x = s[-4:3]
y = t.sort_index()[-3:5]
print(x)
print(y)
z = s[-4:3]+t.sort_index()[-3:5]
print(z)

b    2
c    3
dtype: int64
c    5
d    4
e    2
dtype: int64
b    NaN
c    8.0
d    NaN
e    NaN
dtype: float64
