In [ ]:
msg = "crocoDILE"
price = "125"
sample = "0123456789"

In [ ]:
print(msg.upper())
print(msg.lower())
print(msg.capitalize())
print(msg.startswith('C'))
print(msg.endswith('E'))
print(msg.index('c'))
print(msg.count('o'))
print(price.isdigit())
print('this is shruthi'.capitalize())
print('this is shruthi'.title())

CROCODILE
crocodile
Crocodile
False
True
0
2
True
This is shruthi
This Is Shruthi


In [ ]:
print(sample[0])
print(sample[:])
print(sample[0:3])  #0,1,2
print(sample[:4])
print(sample[4:])

0
0123456789
012
0123
456789


In [ ]:
print(sample[-1])
print(sample[-2:])
print(sample[::-1])
print(sample[-5:-2])

9
89
9876543210
567


In [ ]:
s1 = 'This is Shruthi from TCS'
print(s1.split(' '))

['This', 'is', 'Shruthi', 'from', 'TCS']


In [ ]:
M1 = 'English 75 Maths 80 Science 95'
M2 = M1.split()
print("New List:",M2)
l=[]
for s in M2[1::2]:
  l.append(int(s))
print("Scores list:",l)
print("Total: ",sum(l))
print("Average: ",round(sum(l)/len(l),2))

New List: ['English', '75', 'Maths', '80', 'Science', '95']
Scores list: [75, 80, 95]
Total:  250
Average:  83.33


In [ ]:
M1 = 'English 75 Maths 80 Science 95'
M2 = M1.split()
print("New List:",M2)
l=[]
for word in M2 :
  if word.isdigit() :
    l.append( int(word))
print('Scores List: ',l)
print('Total Scores ' , sum(l))
print('Average',round(sum (l)/len(l),2))

New List: ['English', '75', 'Maths', '80', 'Science', '95']
Scores List:  [75, 80, 95]
Total Scores  250
Average 83.33


In [ ]:
names = 'Shruthi Sony,Sathvik Lucky,Saritha Sari,Balachander Chandu'
N1 = names.split(',')
for i in N1:
  name1 = i.split()
  print("Dear "+name1[1]+'.'+name1[0][0])

Dear Sony.S
Dear Lucky.S
Dear Sari.S
Dear Chandu.B


In [ ]:
weights = [12,11,13,14,15]
dict1={}
for i in weights:
  dict1[i] = round(i*0.45,2)
print(dict1)

{12: 5.4, 11: 4.95, 13: 5.85, 14: 6.3, 15: 6.75}


In [ ]:
visibility = [1,2,3,4,5,6]

dict1={}
for i in visibility:
  if i<=2:
    fog_level = 'ThickFog'
  elif 3<=i<=5:
    fog_level = 'Moderate'
  else:
    fog_level = 'low'
  dict1[i]= fog_level
print(dict1)

{1: 'ThickFog', 2: 'ThickFog', 3: 'Moderate', 4: 'Moderate', 5: 'Moderate', 6: 'low'}


In [ ]:
days = ['M','W','F']
medicines = ['Vit','Ca','Zn']
for d,m in zip(days,medicines):
  dict1[d] = m
print(dict1)

{'M': 'Vit', 'W': 'Ca', 'F': 'Zn'}


In [ ]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
dict3=dict1|dict2
dict3

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}

In [ ]:
sampleDict = {
    "class": {
        "student": {
            "name": "Mike",
            "marks": {
                "physics": 70,
                "history": 80
            }
        }
    }
}
sampleDict['class']['student']['marks']['history']

80

In [ ]:
employees = ['Kelly', 'Emma']
defaults = {"designation": 'Developer', "salary": 8000}
res = dict.fromkeys(employees, defaults)
print(res)

{'Kelly': {'designation': 'Developer', 'salary': 8000}, 'Emma': {'designation': 'Developer', 'salary': 8000}}


In [ ]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"}

# Keys to extract
keys = ["name", "salary"]
dict1={}

for k in keys:
    dict1[k]=sample_dict[k]
print(dict1)

{'name': 'Kelly', 'salary': 8000}


In [ ]:
sample_dict = {
    "name": "Kelly",
    "age": 25,
    "salary": 8000,
    "city": "New york"
}

sample_dict['location'] =sample_dict['city']
del sample_dict['city']
sample_dict

{'name': 'Kelly', 'age': 25, 'salary': 8000, 'location': 'New york'}

In [ ]:
sample_dict = {'a': 100, 'b': 200, 'c': 300}

if 200 in sample_dict.values():
  print("YES")

YES


In [ ]:
sample_dict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}
min_value = min(sample_dict.values())
min_key = next(key for key, value in sample_dict.items() if value == min_value)

# Print the value corresponding to the minimum key
print(sample_dict[min_key])


65


In [ ]:
import numpy as np
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
l = []
for i in sampleArray:
  l.append(i[2])
res = np.array(l)
print(res)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]


In [ ]:
l = [i for i in range(100,200,10)]
l1 = np.array(l)
l2 = l1.reshape(5,2)
print(l2)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print(sampleArray[::2,1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [ ]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
arrayThree = arrayOne + arrayTwo
print(arrayThree)
res = arrayThree **2
print(res)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [ ]:
l = [i for i in range(10,34,1)]
l1 = np.array(l)
l2 = l1.reshape(8,3)
print(l2)
l3 = l2.reshape(4,2,3)
print(l3)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]

 [[22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]]]


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [ ]:
data = np.delete(sampleArray,1,1)
print(data)

newColumn = np.array([[10,10,10]])
data1 = np.insert(data,1,newColumn,1)

print(data1)

[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [ ]:
data = np.delete(sampleArray,0,0)
print(data)

[[82 22 12]
 [53 94 66]]


In [ ]:
import pandas as pd
df = pd.read_csv('Automobile_data.csv')

In [ ]:
df = df.sort_values(by=['price'],ascending=False)
df.head()

In [ ]:
df [['company','price']]
#df['price'].max()

In [ ]:
df1 = df.groupby('company')
print(df1.get_group('toyota'))

In [ ]:
df['company'].value_counts()

In [ ]:
print(csv1.head(5))
print(csv1.tail(5))

In [ ]:
df1 = df.groupby('company')
print(df1['company','average-mileage'].mean())

In [ ]:
prev = 0
for i in range(0,11):
  print('curr:',i)
  sum = prev + i
  print('sum:',sum)
  print('prev:',prev)
  prev = i

In [ ]:
a = 'sony'
for i in range(0,len(a)):
    if i%2 == 0:
      print(a[i])

In [21]:
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
list3 = list1+list2
l=[]
for i in range(0,len(list1)):
  if list1[i]%2 != 0:
    l.append(list1[i])

for i in range(0,len(list2)):
  if list2[i]%2 == 0:
    l.append(list2[i])

print(l)

[25, 35, 40, 60, 90]


In [35]:
a = 1234
print(int(a/10))
print(a%10)

123
4


In [40]:
a =1234
while a > 0:
  b = a%10
  a = a//10
  print(b,end=' ')

4 3 2 1 

In [45]:
for num in range(6):
    for i in range(num):
        print (num, end=" ") #print number
    # new line after each row to display pattern correctly
    print("\n")



1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



In [ ]:
def power(b,p):
  return b**p

print(power(2,5))