In [1]:
n=int(input())#find the sum of primes from 2 to n
l=[]
s=0
for i in range(2,n+1):  #n=5
    flag = 0
    for j in range(2,i): #n=2,3,4
        if i%j == 0:
            flag = 1
            break
        else:
            flag = 0
    if flag == 0:
        l.append(i)

print(sum(l))

5
10


In [ ]:
l=[]
for i in range(2,15):
  for k in range(2,i):
    if i%k==0:
      break
    else:
      l.append(i)
      break

print(l)
print(sum(l))

[3, 5, 7, 9, 11, 13]
48


In [ ]:
a = 11
b =12
c=13
d=14
print('{0} {1} {2}'.format(a,b,c))
print(d)

11 12 13
14


In [ ]:
n = 5
from functools import reduce

input = range(1,n+1)
print(input)

if n==0:
  print(1)
else:
  ans = reduce(lambda x,y : x*y,input)
  print(ans)

In [ ]:
print(1//3)

0


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i-1):
    print('*_',end='')
  print('*')

    *
   *_*
  *_*_*
 *_*_*_*
*_*_*_*_*


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i-1):
    print('* ',end='')
  print('*')

    *
   * *
  * * *
 * * * *
* * * * *


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(i-1):
    print(' ',end='')
  for k in range(n-i):
    print('*_',end='')
  print('*')

*_*_*_*_*
 *_*_*_*
  *_*_*
   *_*
    *


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(1,i+1):
    print('* ',end='')
  print('\r')


* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i):
    print('*',end='')
  print('\r')

    *
   **
  ***
 ****
*****


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(i-1):
    print(' ',end='')
  for k in range(n+1-i):
    print('*',end='')
  print('\r')



*****
 ****
  ***
   **
    *


In [ ]:
n = 5
for i in range(1,n+1):
  for k in range(n+1-i):
    print('* ',end='')
  print('\r')

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
n = 5
for i in range(1,n+1):
  for k in range(n+1-i):
    print(i,end=' ')
  print('\r')

1 1 1 1 1 
2 2 2 2 
3 3 3 
4 4 
5 


In [ ]:
n = 5
for i in range(1,n+1):
  for k in range(n+1-i):
    print(i,end=' ')
    i = i+1
  print('\r')

1 2 3 4 5 
2 3 4 5 
3 4 5 
4 5 
5 


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i):
    print('*',end='')
  print('\r')

for i in range(1,n):
  for j in range( i):
    print(' ',end='')
  for k in range(n-i):
    print('*',end='')
  print('\r')

    *
   **
  ***
 ****
*****
 ****
  ***
   **
    *


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i):
    print('* ',end='')
  print('\r')

for i in range(1,n):
  for j in range( i):
    print(' ',end='')
  for k in range(n-i):
    print('* ',end='')
  print('\r')

    * 
   * * 
  * * * 
 * * * * 
* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [ ]:
n = 5
for i in range(1,n+1):
  for j in range(i-1):
    print(' ',end='')
  for k in range(n+1-i):
    print('* ',end='')
  print('\r')

for i in range(2,n+1):
  for j in range(n-i):
    print(' ',end='')
  for k in range(i):
    print('* ',end='')
  print('\r')

In [ ]:
l = [i for i in range(10,110,10)]
print(l)
print(l[1:-1:2])
l1 = [l[i] for i in range(1,9,2)]
print(l1)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[20, 40, 60, 80]
[20, 40, 60, 80]


In [ ]:
b = '45,35,425'
b.split(',')

['45', '35', '425']

In [3]:
a = [20,10,30,40]
print('a:\n',a)
sorted_list = sorted(a)
print('sorted:\n',sorted_list)
l = len(a)
print('Max:',sorted_list[-1])
print('Min:',sorted_list[0])
print('2nd Max:',sorted_list[-2])
print('2nd Min:',sorted_list[1])

a:
 [20, 10, 30, 40]
sorted:
 [10, 20, 30, 40]
Max: 40
Min: 10
2nd Max: 30
2nd Min: 20


In [ ]:
l1 = [10,20,30,40]
l2 = [20,40,50,60]
l=[]
for i in l2:
  if i not in l1:
    l.append(i)
l1.extend(l)
print(l1)

[10, 20, 30, 40, 50, 60]


In [ ]:
l1 = [23,45,34,76]
l2 = [70,34,94]
avg1 = sum(l1)/len(l1)
print(avg1)

44.5


In [ ]:
l1 = [10,20,30,40,50]
l2 = [30,60,80,40]
avg1 = sum(l1)/len(l1)
print(avg1)
for i in l2:
  if i > avg1:
    l1.append(i)

print(l1)

30.0
[10, 20, 30, 40, 50, 60, 80, 40]


In [ ]:
for i in l2:
  if i > avg1:
    l1.append(i)

print(l1)

[23, 45, 34, 76, 70, 94]


In [ ]:
l1 = [ [29,31], [23,26], [24,25] ]
w = 24
count = 0
for i in l1:
  if i[0]<=w<=i[1]:
    count=count+1
print(count)

2


In [ ]:
m = 4
n= 5
for i in range(0,m):
  for j in range(0,n):
    print('*',end='')
  print('\r')

*****
*****
*****
*****


In [ ]:
m =3
n=3
final = [0]*n
final = [list(final) for i in range(m)]
#print(final)
#start writing code here
for i in range(0,m):
    for j in range(0,n):
        if i==0 or i==m-1 or j==0 or j==n-1:
            final[i][j] = 1
        else:
            final[i][j] = 0

for i in final:
    print(i)

[1, 1, 1]
[1, 0, 1]
[1, 1, 1]


In [ ]:
import numpy as np
a = np.zeros((3,3), dtype='int')
print(a)
print()
for i in range(0,3):
  for j in range(0,3):
    if i==0 or i==2 or j==0 or j==2:
      a[i][j] = 1

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [ ]:
a=chr(123)
print(a)
type(a)

{


str

In [ ]:
s = 'aabupGradaab'.strip('a').strip('b').strip('a')
#print(s[:2]+s[2].upper()+s[3:])
print(s)

upGrad


In [ ]:
s = 'i am sony'
s = s.split(' ')
s.reverse()
print(' '.join(s))

sony am i


In [ ]:
s = 'i am sony'
s = s.split(' ')
w = s[::-1]
print(w)
print(' '.join(w))

['sony', 'am', 'i']
sony am i


In [ ]:
n = 'data SCience'
n = n.lower()
l=[]
words = n.split(' ')
for i in words:
  #l.append(i[0].upper() + i[1:])
  l.append(i.capitalize())

print(l)
print('_'.join(l))

['Data', 'Science']
Data_Science


In [ ]:
#ouoeoY lv Pythn!
vowel = 'aeiouAEIOU'
v=''
c=''
s = 'You love Python!'
for i in s:
  if i in vowel:
    v = v+i
  else:
    c=c+i

print(v+''+c)

ouoeoY lv Pythn!


In [ ]:
s=''
s1 = 'upgrad'
s1 = s1.lower()
s2 = 'upgradScience'
s2 = s2.lower()
l1 =len(s1)
l2 =len(s2)
l3 = min(l1,l2)
for i in range(0,l3):
    if s1[i]!=s2[i]:
      break
    else:
      s=s+s1[i]
if i==0:
  print(-1)
else:
  print(s)



upgrad


In [ ]:
#anagrams problem
s1 = 'senator'
s2 = 'sEnator'
s1 = s1.lower()
s2 =s2.lower()
s=0 #if all chars are same
k=0 #if any char is different
if len(s1)!=len(s2):
  k=k+1
else:
  for i in range(len(s1)):
      if s1.count(s1[i])!=s2.count(s1[i]):
        k=k+1
      else:
        s=s+1

if s>0 and k==0:
  print('True')
else :
  print('False')

True


In [ ]:
s1 = {1,2,3}
s2 = {2,3,4}
s3 = {3,4,5}
set.intersection(s1,s2,s3)
s1.intersection(s2,s3)

{3}

In [ ]:
d={'a':1,'b':2,'d':4,'c':3}
del d['a']
print(d)
print(d.keys())
print(d.values())
print(d.items())

{'b': 2, 'd': 4, 'c': 3}
dict_keys(['b', 'd', 'c'])
dict_values([2, 4, 3])
dict_items([('b', 2), ('d', 4), ('c', 3)])


In [ ]:
l=[8,9,2,2,3,4,5,2,3,4]
d={}
c=1
for i in l:
  if i not in d:
    d[i] = c
  else:
    d[i]=d[i]+1
print(d)
print(list(d.values()))

{8: 1, 9: 1, 2: 3, 3: 2, 4: 2, 5: 1}
[1, 1, 3, 2, 2, 1]


In [ ]:
d = {'Mobile': ['Redmi', 'Samsung', 'Realme'],
'Laptop': ['Dell', 'HP'],
'TV': ['Videocon', 'Sony'] }
print(d)
l=[]
for i in d.keys():
  for j in d[i]:
    l.append((i+'_'+j))

print(l)

{'Mobile': ['Redmi', 'Samsung', 'Realme'], 'Laptop': ['Dell', 'HP'], 'TV': ['Videocon', 'Sony']}
['Mobile_Redmi', 'Mobile_Samsung', 'Mobile_Realme', 'Laptop_Dell', 'Laptop_HP', 'TV_Videocon', 'TV_Sony']


In [4]:
s='([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])([{([{([([([([([([([([([([{{{{[]}}}}])])])])])])])])])])}])}])'
def check(s):
  for i in s:
    if s.count('(')!=s.count(')') or s.count('{')!=s.count('}') or s.count('[')!=s.count(']'):
      return 'No'
    else:
      return 'Yes'

check(s)

'Yes'

In [ ]:
name=input()
age=input()
print(f'Hi {name} ur age after 100 yrs will be {int(age)+100}')
print('Hi {} ur age after 100 yrs will be {}'.format(name,int(age)+100))

sony
25
Hi sony ur age after 100 yrs will be 125
Hi sony ur age after 100 yrs will be 125


In [ ]:
name = input("What is your name: ")
age = int(input("How old are you: "))
year = 2024 - age + 100
print(name + ", you will be 100 years old in the year " + str(year));

What is your name: sony
How old are you: 25
sony, you will be 100 years old in the year 2099


In [ ]:
  a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
  b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  s1 = set(a)
  s2 = set(b)
  s3 = s1&s2
  print(list(s3))

[1, 2, 3, 5, 8, 13]


In [ ]:
l=[]
fruits = ['orangE ', ' apple', 'pear ', ' banana', 'kiwi', 'apple', 'banana']
for i in fruits:
  l.append(i.lower().strip())
print(l)
print(l.count('apple'))
l.reverse()
print(l)
l.sort()
print(l)
print(l.index('apple',1))
l.pop()
del l[0]
print(l)
l.insert(0,'grapes')
l
print(len(l))

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
2
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']
['apple', 'apple', 'banana', 'banana', 'kiwi', 'orange', 'pear']
1
['apple', 'banana', 'banana', 'kiwi', 'orange']
6


In [ ]:
stack = [2,3,4]
stack.append(6)
stack.append(7)
stack
stack.pop()
stack

[2, 3, 4, 6]

In [ ]:
queue = [2,3,4]
queue.append(5)
queue.append(6)
queue.pop(0)
#del queue[0]
queue

[3, 4, 5, 6]

In [ ]:
combs = []
for i in [1,2,3]:
  for j in [2,3,4]:
    if i!=j:
      combs.append((i,j))

combs

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 2), (3, 4)]

In [ ]:
m = ['Mon','Tue','Wed']
a = ['M','T','W']
d={}
for m,a in zip(m,a):
  d[m]=a
print(d)

{'Mon': 'M', 'Tue': 'T', 'Wed': 'W'}


In [ ]:
t = (1,2,3,4)
(a,b,c,d) = t
a,b

(1, 2)

Scenario :
<pre>
Let us assume you are Bike Rider and caught by a Cop and you are asked 2 Details
1. What was your Riding Speed (miles) ?
2. Is it your Birthday Today ?

the cop will be calculating Ticket as per the Details Below :

a. if speed > 80 print 'Big Ticket'
b. if speed between 60 and 80 print 'Small Ticket'
c. if speed < 60 print 'No Ticket'

note : if it is rider's birthday then 5 Miles/Hr will be exempted from Speed and then the ticket will be calculated.

Test Case :
Speed: 82
Birthday: Yes
Output: small Ticket

In [ ]:
speed = int(input('Enter speed: '))
is_bday = input('Is your Bday? Yes/No: ')
if is_bday == 'Yes':
  speed = speed - 5
else:
  speed = speed

if speed > 80:
  print('Big Ticket')
elif 60 <= speed <= 80:
  print('Small Ticket')
else:
  print('No Ticket')

Enter speed: 85
Is your Bday? Yes/No: Yes
Small Ticket


## 🎮 Task : Guess the Number Game
-------------------------------------------------
<pre>
Let us assume there are 2 Players :

Step 1 :  Generate a Random number between 1 and 20 , store in a variable say computerChoice

Step 2 : Ask the user to Enter(Guess) a number between 1 and 20 , Store in a variable say userChoice

Step 3 : Do the Comparision :

        if userChoice > computerChoice print 'Your guess is too High'

        if userChoice < computerChoice print 'Your guess is too Low'

        if userChoice matches with computerChoice print 'Gotcha! You Guessed Right'

<i>
Note: A User can guess/make 6 attempts , after 6 attempts of guessing number print 'Oops! Try Later'
</i>

In [ ]:
#Note: A User can guess/make 6 attempts , after 6 attempts of guessing number print 'Oops! Try Later'
import random
s1 = random.randint(1,20)
s2 = int(input('Enter a number: '))
count = 1
while count<6:
  if s2 > s1:
    print('Your guess is too high')
    s2 = int(input('Enter a number again: '))
    count = count+1
  elif s2 < s1:
    print('Your guess is too low')
    s2 = int(input('Enter a number again: '))
    count = count+1
  else:
    print('Perfect!!')
    break

print('Oops Time up !!')

Enter a number: 4
Your guess is too low
Enter a number again: 22
Your guess is too high
Enter a number again: 22
Your guess is too high
Enter a number again: 12
Your guess is too low
Enter a number again: 56
Your guess is too high
Enter a number again: 23
Oops Time up !!


# Task : 😅 How Long is your Burp ?
----
<pre>
Ask the user to enter his/her Burp Length !

print 'Burp' as per the Input.

eg.

BurpLength = 5 output : 'Burrrrrp'

BurpLength = 45 output : 'Burrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrp'

note: user can enter any Burp Length

In [ ]:
len = int(input('Enter Burp length'))
print('Bu'+'r'*len+'p')
#or
l = ''
for i in range(len):
  l = l + 'r'

print(f'Bu{l}p')

Enter Burp length3
Burrrp
Burrrp


# 🎂 Birthday
---
<pre>
Let us assume it is your friends Birthday , you are provided with information explaining Height of Candles used on CAKE.

candles = [ 2  , 1 , 5 , 3 , 5 , 4 , 5 ]

Objective: You are asked to find Count of Tallest Candle.

In [ ]:
from sys import maxsize
candles = [2,1,3,4,5,2,5,5,1,5]
'''max = max(candles)
print(candles.count(5))'''  #method1

'''max = candles[0]
for i in candles:
  if i > max:                #method2
    max = i'''

candles.sort()
max = candles[-1]      #method3

print('max no: ',max)
print('count of max height: ',candles.count(max))

max no:  5
count of max height:  4


# ❄️ HailStone Sequence Algorithm
---
<pre>
Take a number (says ‘n’) as an input.
Print the value of ‘n’.
while n != 1
a) Print the value of ‘n’.
b) If ‘n’ is odd, calculate the next number as n*3+1.
c) If ‘n’ is even, calculate the next number as n/2.

Example:
Input : 10
Output (Hailstone Sequence): 10 -> 5 -> 16 -> 8 -> 4 -> 2 ->1
Input : 17
Output (Hailstone Sequence): 17 -> 52 -> 26 -> 13 -> 40 -> 20 ->10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1

Objective: translate the given algorithm into python program/app.


In [ ]:
n = int(input('Enter input: '))
print('Input:',n,end= ' ')
while n!=1:
  if n%2 == 0:
    n = n//2
  elif n%2 == 1:
    n = n*3+1
  print(n,end=' ')

Enter input: 10
Input: 10 5 16 8 4 2 1 

#  🫙 Swap the Cup
---
<pre>
Cup Swapping


There are three cups on a table, at positions A, B and C. At the start, there is a ball hidden under the cup at position B. However, I perform a number of swaps on the cups, which is notated as two letters. For example, if I swap the cups at positions A and B, I could notate this as AB or BA. Create a function which returns the letter position that the ball is at, once I finish swapping the cups. The swaps will be given to you as a list.
Worked Example cup_swapping(['AB', 'CA', 'AB']) ➞ 'C'
Ball begins at position B.
Cups A and B swap, so ball is at position A. Cups C and A swap, so ball is at position C. Cups A and B swap, but the ball is at position C, so it doesn't move.
Examples
cup_swapping(['AB', 'CA']) ➞ 'C'
cup_swapping(['AC', 'CA', 'CA', 'AC']) ➞ 'B'
cup_swapping(['BA', 'AC', 'CA', 'BC']) ➞ 'A'


In [ ]:
pos = 'B'
l = ['AB', 'CA']
for i in l:
  if pos in i:
    if pos == i[0]:
      pos = i[1]
    else:
      pos = i[0]
print(pos)

C


In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
print(lst[3][1][2][0])

hello


**Graded Assignment - 1:**

In a school, there are total 100 students numbered from 1 to 100. You’re given three lists named ‘C’, ‘F’, and ‘H’, representing students who play cricket, football, and hockey, respectively. Based on this information, find out and print the following:
- Students who play all the three sports
- Students who play both cricket and football but don’t play hockey
- Students who play exactly two of the sports
- Students who don’t play any of the three sports

In [ ]:
C = [7, 8, 9, 18, 20, 21, 25, 26, 27, 31, 32, 34, 35, 36, 40, 43, 45, 47, 53, 58, 62, 67, 68, 71, 72, 74, 75, 76, 80, 81, 82, 90, 93, 95, 97, 99]
F = [1, 7, 10, 13, 16, 22, 24, 29, 30, 32, 34, 39, 40, 43, 44, 48, 56, 60, 65, 68, 69, 73, 77, 78, 90, 93, 94, 95, 96]
H = [5, 12, 14, 17, 20, 21, 22, 25, 28, 30, 37, 38, 39, 40, 42, 44, 57, 59, 61, 62, 67, 71, 75, 76, 77, 82, 83, 86, 87, 92, 94, 95]

In [ ]:
C1 = set(C)
print(len(C1))
F1 = set(F)
print(len(F1))
H1 = set(H)
print(len(H1))

36
29
32


In [ ]:
#Question 1: - Students who play all the three sports
print(C1&F1&H1)   # intersections of all games

{40, 95}


In [ ]:
#Question 2: - Students who play both cricket and hockey but don’t play football
#only who plays cricket and hockey
CH = C1&H1
print('intersection of cricket and hockey: ',CH)  #this includes football players also
print('only who plays cricket and hockey: ',CH - (C1&F1&H1))  #9 elemnts

intersection of cricket and hockey:  {67, 71, 40, 75, 76, 82, 20, 21, 25, 62, 95}
only who plays cricket and hockey:  {67, 71, 75, 76, 82, 20, 21, 25, 62}


In [ ]:
# only who plays hockey and football
HF = H1&F1
print('intersection of hockey and football: ',HF)  #this includes cricket players also
print('only who plays hockey and football: ',HF - (C1&F1&H1))  #6 elements

intersection of hockey and football:  {39, 40, 44, 77, 22, 94, 30, 95}
only who plays hockey and football:  {39, 44, 77, 22, 30, 94}


In [ ]:
# only who plays cricket and football
CF = C1&F1
print('intersection of cricket and football: ',CF)  #this includes hockey players also
print('only who plays cricket and football: ',CF - (C1&F1&H1))  #7 elements

intersection of cricket and football:  {32, 34, 68, 7, 40, 43, 90, 93, 95}
only who plays cricket and football:  {32, 34, 68, 7, 43, 90, 93}


In [ ]:
#Question 3:  - Students who play exactly two of the sports
#len(only who plays hockey and cricket) + len(only who plays hockey and football) + len(only who plays cricket and football)
#9+6+7

In [ ]:
#Question 4:  - Students who don’t play any of the three sports
total = set(range(1,101))
print(total)
noplay = total - (C1|H1|F1)
print(noplay)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100}
{2, 3, 4, 6, 11, 15, 19, 23, 33, 41, 46, 49, 50, 51, 52, 54, 55, 63, 64, 66, 70, 79, 84, 85, 88, 89, 91, 98, 100}


The `netflix` dictionary contains a list of 100 titles along with their total number of views in the past. Based on the keys and values provided in this dictionary, answer the questions given below.

In [ ]:
netflix = {'The Debt Collector': 1821195, 'Act of Vengeance': 2804479, 'Paradise Lost': 2195477, "Gerald's Game": 3650626, 'Long Shot': 638440, 'Mak Cun': 1010311, 'Our Souls at Night': 3028705, 'Out of Thin Air': 2681938, "Paul Hollywood's Big Continental Road Trip": 230689, 'Satu Hari': 1012350, 'Monster High: Boo York, Boo York': 1526025, 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 2762103, 'Domino': 872663, 'TUNA GIRL': 2574816, '5CM': 2647713, 'Animal World': 220789, 'Hold the Dark': 2307432, 'Lessons from a School Shooting: Notes from Dunblane': 2419534, 'Made in Mexico': 3653712, 'Single': 239278, 'The 3rd Eye': 196138, 'The Sinking Of Van Der Wijck': 2831856, 'Two Catalonias': 1337119, 'Bobby Sands: 66 Days': 2005623, 'Bard of Blood': 744998, 'Deliha 2': 3638900, 'Dragons: Rescue Riders': 3241239, 'In the Shadow of the Moon': 1213329, 'Skylines': 1840094, 'Sturgill Simpson Presents Sound & Fury': 1915540, 'The Politician': 1019394, 'Weeds on Fire': 2273090, 'Much Loved': 3039852, 'Joseph: King of Dreams': 1734449, 'Malaal': 1926128, 'The Grandmaster': 2549410, 'The Inmate': 130965, 'The Hurricane Heist': 2191538, 'Def Comedy Jam 25': 1392697, 'Restless Creature: Wendy Whelan': 2474412, 'Print the Legend': 548250, 'Birders': 3478883, 'Furie': 2755115, 'Leap!': 1401638, 'Oh! Baby (Malayalam)': 839139, 'Oh! Baby (Tamil)': 2691505, 'USS Indianapolis: Men of Courage': 3286014, 'A Wrinkle in Time': 1258861, 'Teach Us All': 2428947, 'White Island': 1152905, 'Inside Man: Most Wanted': 2812661, 'Jeff Dunham: Beside Himself': 2930368, 'China Salesman': 3377292, 'Swearnet: The Movie': 949689, 'The Bar': 620655, 'Manmadhudu 2': 1842761, 'Team Kaylie': 359856, 'Under the Eiffel Tower': 2298237, 'Audrie & Daisy': 1573055, 'Iliza Shlesinger: Confirmed Kills': 365220, 'BONDING': 1664242, 'Do Paise Ki Dhoop Chaar Aane Ki Baarish': 2770879, '20 Feet From Stardom': 2931730, 'In Darkness': 3248749, 'Gaga: Five Foot Two': 3719550, 'The Bad Batch': 3656264, 'SMOSH: The Movie': 3697506, 'King of Boys': 584112, 'Merry Men: The Real Yoruba Demons': 2035595, "Sarah's Key": 1337902, 'The Wedding Party 2: Destination Dubai': 1471204, 'Vagabond': 1600432, 'Battlefish': 723021, 'DRAGON PILOT: Hisone & Masotan': 602919, 'Hilda': 54948, 'Maniac': 1348196, 'Quincy': 2601704, 'Rafinha Bastos: Ultimatum': 3469996, 'The Good Cop': 2265521, 'Between Two Ferns: The Movie': 3146508, 'Criminal: France': 2021409, 'Criminal: Germany': 658824, 'Criminal: Spain': 3078634, 'Criminal: UK': 2721398, 'Daddy Issues': 2119035, "Inside Bill's Brain: Decoding Bill Gates": 1755104, 'The Hockey Girls': 2000507, 'Travel Mates 2': 707260, 'True: Tricky Treat Day': 3213199, 'Two Sentence Horror Stories': 2438329, 'Mad World': 2281773, 'Mobile Suit Gundam UC': 778879, 'The Bund': 1729892, 'The First Line': 674591, 'Maynard': 84986, 'Monkey Twins': 3277179, 'Bitcoin Heist': 1450158, 'I Am Not Madame Bovary': 2763830, 'Vincent N Roxxy': 1961810, "Chef's Table: France": 2065738}

In [ ]:
#Question 1: There's an Indian movie in the dictionary named `Do Paise Ki Dhoop Chaar Aane Ki Baarish`. What is the number of views for this movie?
netflix['Do Paise Ki Dhoop Chaar Aane Ki Baarish']

2770879

In [ ]:
# Question 2: Which of the shows is the most and least popular in terms of number of views?
l=[]
for i,j in netflix.items():
  l.append(j)

print(max(l))  #to find maximun
print(min(l))  #to find minimum

k = list(netflix.keys())
v = list(netflix.values())
print(v.index(54948))  #74 is index  #min value 54948
print(k[74])

3719550
54948
74
Hilda


In [ ]:
# Question 3: Netflix has just recieved the number of views for the last week as well. Add these views to the total views and find the most popular title in terms of views.
# Also find out how many views this title has?

In [ ]:
netflix_last_week = {'The Debt Collector': 229218, 'Act of Vengeance': 191468, 'Paradise Lost': 167846, "Gerald's Game": 113298, 'Long Shot': 15190, 'Mak Cun': 244581, 'Our Souls at Night': 188095, 'Out of Thin Air': 183961, "Paul Hollywood's Big Continental Road Trip": 207967, 'Satu Hari': 226211, 'Monster High: Boo York, Boo York': 265919, 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 192246, 'Domino': 190538, 'TUNA GIRL': 301819, '5CM': 154371, 'Animal World': 228227, 'Hold the Dark': 222938, 'Lessons from a School Shooting: Notes from Dunblane': 256580, 'Made in Mexico': 199790, 'Single': 155517, 'The 3rd Eye': 251349, 'The Sinking Of Van Der Wijck': 153797, 'Two Catalonias': 189422, 'Bobby Sands: 66 Days': 202461, 'Bard of Blood': 241928, 'Deliha 2': 304552, 'Dragons: Rescue Riders': 155149, 'In the Shadow of the Moon': 222999, 'Skylines': 118737, 'Sturgill Simpson Presents Sound & Fury': 43590, 'The Politician': 11902, 'Weeds on Fire': 243382, 'Much Loved': 190123, 'Joseph: King of Dreams': 46104, 'Malaal': 70961, 'The Grandmaster': 44908, 'The Inmate': 19574, 'The Hurricane Heist': 167696, 'Def Comedy Jam 25': 208075, 'Restless Creature: Wendy Whelan': 22976, 'Print the Legend': 161584, 'Birders': 257668, 'Furie': 282266, 'Leap!': 124338, 'Oh! Baby (Malayalam)': 18203, 'Oh! Baby (Tamil)': 131481, 'USS Indianapolis: Men of Courage': 76558, 'A Wrinkle in Time': 169365, 'Teach Us All': 50378, 'White Island': 299779, 'Inside Man: Most Wanted': 123346, 'Jeff Dunham: Beside Himself': 283561, 'China Salesman': 182041, 'Swearnet: The Movie': 63809, 'The Bar': 41243, 'Manmadhudu 2': 261349, 'Team Kaylie': 101283, 'Under the Eiffel Tower': 83650, 'Audrie & Daisy': 106092, 'Iliza Shlesinger: Confirmed Kills': 255103, 'BONDING': 202683, 'Do Paise Ki Dhoop Chaar Aane Ki Baarish': 32329, '20 Feet From Stardom': 165178, 'In Darkness': 95259, 'Gaga: Five Foot Two': 36638, 'The Bad Batch': 197820, 'SMOSH: The Movie': 196519, 'King of Boys': 49332, 'Merry Men: The Real Yoruba Demons': 293229, "Sarah's Key": 178523, 'The Wedding Party 2: Destination Dubai': 51211, 'Vagabond': 116831, 'Battlefish': 5448, 'DRAGON PILOT: Hisone & Masotan': 281873, 'Hilda': 21348, 'Maniac': 268187, 'Quincy': 139696, 'Rafinha Bastos: Ultimatum': 105449, 'The Good Cop': 73230, 'Between Two Ferns: The Movie': 135600, 'Criminal: France': 243469, 'Criminal: Germany': 285211, 'Criminal: Spain': 45184, 'Criminal: UK': 117056, 'Daddy Issues': 267329, "Inside Bill's Brain: Decoding Bill Gates": 64083, 'The Hockey Girls': 114146, 'Travel Mates 2': 21088, 'True: Tricky Treat Day': 116504, 'Two Sentence Horror Stories': 274471, 'Mad World': 225244, 'Mobile Suit Gundam UC': 47306, 'The Bund': 146872, 'The First Line': 148861, 'Maynard': 87252, 'Monkey Twins': 199274, 'Bitcoin Heist': 41105, 'I Am Not Madame Bovary': 57841, 'Vincent N Roxxy': 207453, "Chef's Table: France": 200536}

In [ ]:
for i,j in zip(netflix,netflix_last_week):
  if i==j:
    netflix[i] = netflix[i]+netflix_last_week[i]

print(netflix)
print(max(list(netflix.values())))

{'The Debt Collector': 2050413, 'Act of Vengeance': 2995947, 'Paradise Lost': 2363323, "Gerald's Game": 3763924, 'Long Shot': 653630, 'Mak Cun': 1254892, 'Our Souls at Night': 3216800, 'Out of Thin Air': 2865899, "Paul Hollywood's Big Continental Road Trip": 438656, 'Satu Hari': 1238561, 'Monster High: Boo York, Boo York': 1791944, 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 2954349, 'Domino': 1063201, 'TUNA GIRL': 2876635, '5CM': 2802084, 'Animal World': 449016, 'Hold the Dark': 2530370, 'Lessons from a School Shooting: Notes from Dunblane': 2676114, 'Made in Mexico': 3853502, 'Single': 394795, 'The 3rd Eye': 447487, 'The Sinking Of Van Der Wijck': 2985653, 'Two Catalonias': 1526541, 'Bobby Sands: 66 Days': 2208084, 'Bard of Blood': 986926, 'Deliha 2': 3943452, 'Dragons: Rescue Riders': 3396388, 'In the Shadow of the Moon': 1436328, 'Skylines': 1958831, 'Sturgill Simpson Presents Sound & Fury': 1959130, 'The Politician': 1031296, 'Weeds on Fire':